/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A reusable renderer instance that maintains a single RenderService.
 *
 * This class solves the v8 isolate issue by reusing the same service instance
 * across multiple renders, allowing the renderer pool to properly manage v8 isolates.
 * Use this instead of creating a new service for each render when you need to render
 * multiple times, especially with different output modes.
 *
 * # Example
 *
 * ```javascript
 * const { Renderer } = require('@dinja/core');
 *
 * // Create a renderer instance (loads engine once)
 * const renderer = new Renderer();
 *
 * // Reuse the same instance for multiple renders
 * const result1 = await renderer.render({
 *   settings: { output: 'html', minify: false },
 *   mdx: { 'file1.mdx': '# Hello' }
 * });
 *
 * const result2 = await renderer.render({
 *   settings: { output: 'schema', minify: false },
 *   mdx: { 'file2.mdx': '# World' }
 * });
 * ```
 */
export declare class Renderer {
  /**
   * Creates a new Renderer instance.
   *
   * The engine is loaded once during initialization and reused for all subsequent renders.
   * This prevents v8 isolate issues when rendering with different modes.
   *
   * # Arguments
   * * `config` - Optional configuration object with:
   *   - `maxCachedRenderers` - Maximum number of cached renderers (default: 4)
   *   - `maxBatchSize` - Maximum number of files in a batch request (default: 1000)
   *   - `maxMdxContentSize` - Maximum MDX content size per file in bytes (default: 10 MB)
   *   - `maxComponentCodeSize` - Maximum component code size in bytes (default: 1 MB)
   */
  constructor(config?: RendererConfig | undefined | null)
  /**
   * Renders MDX content using the reusable service instance.
   *
   * # Arguments
   * * `input` - JSON string containing:
   *   - `settings`: Object with `output` ("html", "javascript", "schema", or "json"),
   *     `minify` (boolean)
   *   - `mdx`: Object mapping file names to MDX content strings
   *   - `components`: Optional object mapping component names to component definitions.
   *     Components can be specified as either:
   *     - Simple strings: `{ "Button": "function Component(props) { ... }" }`
   *     - Full objects: `{ "Button": { "code": "...", "docs": "..." } }`
   *
   * # Returns
   * JSON string containing:
   * - `total`: Total number of files processed
   * - `succeeded`: Number of files that rendered successfully
   * - `failed`: Number of files that failed to render
   * - `errors`: Array of error objects with `file` and `message` keys
   * - `files`: Object mapping file names to render outcomes
   *
   * # Errors
   * - Throws `Error` if the request is invalid (e.g., resource limits exceeded, invalid input)
   * - Throws `Error` if an internal error occurs during rendering
   */
  render(input: string): string
}

/** Configuration options for the Renderer */
export interface RendererConfig {
  /** Maximum number of cached renderers (default: 4) */
  maxCachedRenderers?: number
  /** Maximum number of files in a batch request (default: 1000) */
  maxBatchSize?: number
  /** Maximum MDX content size per file in bytes (default: 10 MB) */
  maxMdxContentSize?: number
  /** Maximum component code size in bytes (default: 1 MB) */
  maxComponentCodeSize?: number
}
